describe('Editar Empresa', function () {
  it('Desde login hasta editar una empresa', function () {
    cy.visit('http://localhost:3002')
    cy.get('.user').find('input').type('admin')
    cy.get('.password').find('input').type('admin')
    cy.get('button').contains('Iniciar Sesión').click()
    cy.wait(1500)
    cy.get('.empresa2').click()
    cy.wait(1000)
    cy.get('.editarEmpresa').click()
    cy.wait(1000)
    cy.get('.nombre').find('input').type('{selectall}{del}AX-Productions')
    cy.wait(600)
    cy.get('.actividadComercial').find('input').type('{selectall}{del}Creación de juegos de video')
    cy.wait(600)
    cy.get('.razonSocial').find('input').type('{selectall}{del}Productores AX3')
    cy.wait(600)
    cy.get('.editar').click()
    cy.wait(1500)
    // cy.get('.direccion').find('input').type('Kennedy Nueva. Av. Orión Llaguno Márquez')
    // cy.get('.ruc').find('input').type('1300752559001')
    // cy.get('button').contains('Crear Empresa').click()
    // cy.url().should('include', '/empresas')
    // cy.wait(600)
  })
})

/* describe('Eliminar Empresa', function () {
  it('Desde login hasta eliminar empresa y ver la info actualizada', function () {
    cy.visit('http://localhost:3002')
    cy.get('.user').find('input').type('admin')
    cy.get('.password').find('input').type('admin')
    cy.get('button').contains('Iniciar Sesión').click()
    cy.wait(1500)
    cy.get('.AX-Productions').click()
    cy.get('.eliminarEmpresa').click()
    cy.get('.eliminar').click()
    cy.wait(1500)
  })
}) */
