DROP DATABASE IF EXISTS i2solutions_development;
CREATE DATABASE i2solutions_development;
USE i2solutions_development;


CREATE TABLE persona(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  nombres CHAR(100) NOT NULL,
  apellidos CHAR(100) NOT NULL,
  rol CHAR(100) NOT NULL,
  cedula CHAR(100) NOT NULL,
  correo CHAR(100) NOT NULL,
  fecha_nacimiento CHAR(100) NOT NULL,
  perfil_ocupacional CHAR(100) NOT NULL,
  usuario CHAR(100) NOT NULL,
  clave TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)ENGINE = InnoDB;

CREATE TABLE novedad(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  descripcion CHAR(100) NOT NULL,
  foto_url CHAR(100) NOT NULL,
  prioridad CHAR(100) NOT NULL,
  estado CHAR(100) NOT NULL,
  fecha_atencion CHAR(100) NOT NULL,
  fecha_nacimiento CHAR(100) NOT NULL,
  perfil_ocupacional CHAR(100) NOT NULL,
  usuario CHAR(100) NOT NULL,
  clave TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)ENGINE = InnoDB;