require('./create_puestos')
require('./create_novedades')
require('./create_counters')
require('./create_areas')
require('./create_equipos_proteccion')
require('./create_riesgos')
require('./create_puesto')
